CREATE SCHEMA IF NOT EXISTS `hms` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
GRANT ALL PRIVILEGES ON *.* TO 'HD'@'localhost' IDENTIFIED BY PASSWORD '*A4B6157319038724E3560894F7F932C8886EBFCF' WITH GRANT OPTION;

GRANT ALL PRIVILEGES ON `hs`.* TO 'HD'@'localhost';

GRANT ALL PRIVILEGES ON `test`.* TO 'HD'@'localhost' WITH GRANT OPTION;