
 
 
 <form method="post" action="body_success_permission.php">
 <table class="table">
			              <thead>
			                <tr>
			                  <th class="style2">Permission</th>
			                  <th class="style1" id="1">Housing Department</th>
			                  <th class="style1" id="2">Supervisor</th>
			                  <th class="style1" id="3"> Student</th>
			                </tr>
			              </thead>
			              <tbody>
			                <tr>
			                  <td class="style2">Housing  Request</td>
			                  <td class="style1">&nbsp;<label><input type="checkbox" name=hd[] value="1"  ></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=sup[] value="1" >  </label></td>
			                  <td>
													<label>
														<input type="checkbox"name=std[]  value="1" ></label></td>
			                </tr>
			                <tr>
			                  <td class="style2">Move  Request</td>
			                  <td class="style1">
													<label>
														<input type="checkbox" name=hd[] value="2"  ></label></td>
			                  <td>
													<label>
														<input type="checkbox"  name=sup[] value="2" ></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=std[] value="2"  ></label></td>
			                </tr>
			                  <tr>
			                  <td class="style2">Renew  Request</td>
			                  <td class="style1">
													<label>
														<input type="checkbox" name=hd[] value="3"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=sup[] value="3"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=std[] value="3" ></label></td>
			                  </tr>
                              <tr>
			                  <td class="style2">View Penalties/Fines</td>
			                  <td class="style1">
													<label>
														<input type="checkbox" name=hd[] value="4"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=sup[] value="4"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=std[] value="4"></label></td>
			                  </tr>
                              <tr>
			                  <td class="style2">Send Daily Documents </td>
			                  <td class="style1">
													<label>
														<input type="checkbox" name=hd[] value="5"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=sup[] value="5"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=std[] value="5"></label></td>
			                  </tr>
                              <tr>
			                  <td class="style2">Send Special Needs Housing  </td>
			                  <td class="style1">
													<label>
														<input type="checkbox" name=hd[] value="6"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=sup[] value="6"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=std[] value="6"></label></td>
			                  </tr>
                              <tr>
			                  <td class="style2">View Housing  Request</td>
			                  <td class="style1">
													<label>
														<input type="checkbox" name=hd[] value="7"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=sup[] value="7"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=std[] value="7"></label></td>
			                  </tr>
                              <tr>
			                  <td class="style2">Accept/Reject Student in House</td>
			                  <td class="style1">
													<label>
														<input type="checkbox" name=hd[] value="8"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=sup[] value="8"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=std[] value="8"></label></td>
			                  </tr>
                              <tr>
			                  <td class="style2">View Daily Documents</td>
			                  <td class="style1">
													<label>
														<input type="checkbox" name=hd[] value="9"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=sup[] value="9"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=std[] value="9"></label></td>
			                  </tr>
                              <tr>
			                  <td class="style2">View Special Needs Housing</td>
			                  <td class="style1">
													<label>
														<input type="checkbox" name=hd[] value="10"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=sup[] value="10"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=std[] value="10"></label></td>
			                  </tr>
			                <tr>
			                  <td class="style2">Fill Penalties/Fines</td>
			                  <td class="style1">
													<label>
														<input type="checkbox" name=hd[] value="11"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=sup[] value="11"></label></td>
			                  <td>
													<label>
														<input type="checkbox" name=std[] value="11"></label></td>
			                </tr>
			                <tr>
			                  <td class="style2" colspan="4">
											&nbsp;</td>
			                </tr>
			                
			                
								
										
			              </tbody>
			            </table>
						           
	                                       <div class="col-md-12">
												&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
												<button class="btn btn-default" type="reset">
													      Reset
												</button> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;
												<button class="btn btn-primary" type="submit" name="sub">
													<i class="fa fa-save"></i>
													Submit
												</button>
											&nbsp;</div></form>
											