
    <footer>
         <div class="container">
         
            <div class="copy text-center">
              
            </div>
            
         </div>
      </footer>
      <link href="vendors/datatables/dataTables.bootstrap.css" rel="stylesheet" media="screen">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
	 <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
	 <script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	  <script src="vendors/datatables/js/jquery.dataTables.min.js"></script>

    <script src="vendors/datatables/dataTables.bootstrap.js"></script>
    <script src="bootstrap/js/bootstrap.min.js"></script>
	 

    <script src="js/custom.js"></script>
    <script src="js/tables.js"></script>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
   
    <!-- jQuery UI -->
   
    <!-- Include all compiled plugins (below), or include individual files as needed -->
   
  </body>
</html>