</div>
   
      <link href="vendors/datatables/dataTables.bootstrap.css" rel="stylesheet" media="screen">
     <link rel="stylesheet" type="text/css" href="vendors/bootstrap-wysihtml5/src/bootstrap-wysihtml5.css"></link> 
    <link rel="stylesheet" type="text/css" href="vendors/bootstrap-wysihtml5/src/bootstrap-wysihtml5.css"></link> 

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
	 <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
	 <script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
	  <script src="vendors/datatables/js/jquery.dataTables.min.js"></script>

    <script src="vendors/datatables/dataTables.bootstrap.js"></script>
    <script src="bootstrap/js/bootstrap.min.js"></script>
	 

    <script src="js/custom.js"></script>
    <script src="js/tables.js"></script>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
   
    <!-- jQuery UI -->
   
    <!-- Include all compiled plugins (below), or include individual files as needed -->
   
   
   
    <script src="vendors/bootstrap-wysihtml5/lib/js/wysihtml5-0.3.0.js"></script>
    <script src="vendors/bootstrap-wysihtml5/src/bootstrap-wysihtml5.js"></script>

    <script src="vendors/ckeditor/ckeditor.js"></script>
    <script src="vendors/ckeditor/adapters/jquery.js"></script>

    <script type="text/javascript" src="vendors/tinymce/js/tinymce/tinymce.min.js"></script>

  </body>
</html>